#Hugo configuration
title = "Projects"
baseURL = "https:\/\/eldomain.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
